apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: olympics
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: olympics
spec:
  host: olympics
  subsets:
  - name: green
    labels:
      fd_version: green
  - name: blue
    labels:
      fd_version: blue
---      
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: olympics
spec:
  gateways:
    - olympics 
  hosts:
    - olympics    
  http:
  - match:
    - uri:
        prefix: /version
    route:
    - destination:
        port:
          number: 8088
        host: olympics
        subset: green
      weight: ${{FD_KN_OLD_WEIGHT}} 
    - destination:
        port:
          number: 8088
        host: olympics     
        subset: blue   
      weight: ${{FD_KN_NEW_WEIGHT}} 