package model;

import java.util.List;

import model.common.AppModule;

import oracle.jbo.Row;
import oracle.jbo.server.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Sep 08 13:06:41 CDT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl
  extends ApplicationModuleImpl
  implements AppModule
{
  /**
   * This is the default constructor (do not remove).
   */
  public AppModuleImpl()
  {
  }

  /**
   * Container's getter for MedalsVO.
   * @return MedalsVO
   */
  public MedalsVOImpl getMedalsVO()
  {
    return (MedalsVOImpl) findViewObject("MedalsVO");
  }

  public long getLong()
  {
    return 5;
  }

  public List<Row> getMedals()
  {
    return getMedalsVO().getMedals();
  }
}

